In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
# array ke particular part ko ek variable ma save krwa ke
# slice krke uski value change krdu tu ab srf uss vaiable ma hi wu sliced value
# change nhi hungi balke original array ma b change hujaegi
sliced = arr[:6]
sliced [:]=55
print("slice array",sliced)
print("orig array",arr)


slice array [55 55 55 55 55 55]
orig array [55 55 55 55 55 55  6  7  8  9 10]


In [12]:
#this happens to avoid memory issue if you dont want this to happen create a copy of array and then modify it 
arr=np.arange(0,11)
arr_copy = arr.copy()

arr_copy[:]=100
print("orig array",arr)
print("copied array",arr_copy)

orig array [ 0  1  2  3  4  5  6  7  8  9 10]
copied array [100 100 100 100 100 100 100 100 100 100 100]


In [14]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[1,2]
# slicig specific part from a 2d array
arr_2d[1:,:]

arr_2d[:2,1:]
# :2 means 1st and 2nd row
# 1: mean 1st and 2nd row ma 1 index ke baad wale

array([[20, 25, 30],
       [35, 40, 45]])

In [25]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [27]:
arr[bool_arr]
arr[arr<5]
# CONDITIONAL SELECTION

array([0, 1, 2, 3, 4])

In [29]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [40]:
# Ex:
# new 2d arr of 50 em and then reshape it in to 5x10 and then slice it
arr_2d = np.arange(50)
arr_2d = arr_2d.reshape(5,10)
arr_2d[1:3,3:5]


array([[13, 14],
       [23, 24]])

In [45]:
# basic numpy error operations b han kch arr*arr , arr/100 etc
np.sqrt(arr)
np.max(arr)
np.sin(arr)
# UNIVERSAL ARRAYS FUNC - visit docs...

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])